version: '3.7'

services:
  reverse:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates/server.crt:/etc/nginx/server.crt
      - ./nginx/certificates/server.key:/etc/nginx/server.key
      - ./nginx/certificates/dhparam.pem:/etc/nginx/dhparam.pem
    depends_on:
      - wordpress